# Generated by Django 6.0.7 on 2026-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0002_alter_users_last_active_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
