# Generated by Django 6.0.7 on 2026-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0003_users_is_staff_alter_permissions_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='role_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
