# Generated by Django 6.0.7 on 2026-08-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0004_roles_is_protected_roles_role_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
    ]
