# Generated by Django 6.0.7 on 2026-08-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0005_rename_role_id_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('FORGOT_PASSWORD', 'Forgot Password')], max_length=30),
        ),
    ]
