# Generated by Django 6.0.7 on 2026-08-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0006_alter_verificationrequest_otp_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_verified',
            new_name='has_changed_password',
        ),
    ]
