# Generated by Django 5.2.7 on 2026-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0008_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
