# Generated by Django 6.0.7 on 2026-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0010_alter_users_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
