# Generated by Django 6.0.7 on 2026-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0011_alter_roles_role_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=50),
        ),
    ]
