# Generated by Django 6.0.7 on 2026-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0012_alter_roles_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='barangay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
