# Generated by Django 6.0.7 on 2026-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0013_users_barangay_users_birth_date_users_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='province',
        ),
        migrations.RemoveField(
            model_name='users',
            name='region',
        ),
        migrations.AddField(
            model_name='users',
            name='barangay_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='province_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='region_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
