# Generated by Django 6.0.7 on 2026-10-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0014_remove_users_barangay_remove_users_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='has_changed_password',
            new_name='must_change_password',
        ),
    ]
