[pytest]
DJANGO_SETTINGS_MODULE = config.settings.base
python_files = test_*.py *_test.py
addopts =
    --cov=apps
    --cov=external
    --cov=shared
    --reuse-db
    --cov-branch
    --cov-report=term-missing
    --cov-report=html:htmlcov