# Generated by Django 6.0.7 on 2026-09-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('audit_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Creation of a new entity'), ('UPDATE', 'Updated an existing entity'), ('DEACTIVATE', 'Deactivated an account'), ('STATUS_CHANGE', 'Status changed on a hazard report'), ('SEVERITY_CHANGE', 'Severity changed on a hazard report')], max_length=50)),
                ('module', models.CharField(choices=[('USERS', 'Users'), ('EMPLOYEES', 'Employees'), ('ROLES', 'Roles'), ('REPORTS', 'Reports')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='apps_audits_content_783bf0_idx'), models.Index(fields=['action', 'module'], name='apps_audits_action_cb65b3_idx')],
            },
        ),
    ]
