# Generated by Django 5.2.7 on 2026-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogs',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='module',
            field=models.CharField(choices=[('USER', 'User'), ('EMPLOYEE', 'Employee'), ('ROLE', 'Role'), ('REPORT', 'Report')], max_length=50),
        ),
    ]
