# Generated by Django 6.0.7 on 2026-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_audits', '0002_alter_auditlogs_options_alter_auditlogs_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='audit_log_number',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
