# Generated by Django 6.0.7 on 2026-09-23 11:00

import apps.audits.models.audit_log_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_audits', '0003_auditlogs_audit_log_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='audit_log_number',
            field=models.CharField(db_index=True, default=apps.audits.models.audit_log_model._generate_audit_log_number, max_length=20, unique=True),
        ),
    ]
