# Generated by Django 6.0.7 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_audits', '0004_alter_auditlogs_audit_log_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='audit_log_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
