from . import env


SECURE_SSL_REDIRECT: bool = env.SECURE_SSL_REDIRECT

SESSION_COOKIE_DOMAIN: str = env.COOKIE_DOMAIN

CSRF_COOKIE_DOMAIN: str = env.COOKIE_DOMAIN
CSRF_TRUSTED_ORIGINS: list[str] = env.TRUSTED_ORIGINS

CORS_ALLOWED_ORIGINS: list[str] = env.TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS: bool = True