# Generated by Django 6.0.7 on 2026-09-02 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardCategories',
            fields=[
                ('hazard_id', models.AutoField(primary_key=True, serialize=False)),
                ('hazard_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardReports',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('severity', models.CharField(blank=True, choices=[('P1', 'P1 - Critical (Immediate Danger)'), ('P2', 'P2 - High (Significant Hazard)'), ('P3', 'P3 - Medium (Standard Hazard)'), ('P4', 'P4 - Low (Minor Concern)'), ('P5', 'P5 - Very Low (Cosmetic/Informational)')], db_index=True, max_length=2, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New - Newly Submitted'), ('OPEN', 'Open - Assigned to Officer'), ('IN_PROGRESS', 'In Progress - Being worked on/Report Verification'), ('PENDING', 'Pending - Invalid/Insufficient Information'), ('ON_HOLD', 'On Hold - Out of Jurisdiction/Need External Department'), ('UNDER_REPAIR', 'Under Repair - Dispatched Engineers'), ('RESOLVED', 'Resolved - Issue is solved but needs user verification'), ('CLOSED', 'Closed - Automatically or manually closed')], db_index=True, default='NEW', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hazard_reports', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_reports', to='apps_reports.hazardcategories')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HazardImages',
            fields=[
                ('hazard_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps_reports.hazardreports')),
            ],
        ),
    ]
