# Generated by Django 6.0.7 on 2026-09-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('report_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps_reports.hazardreports')),
            ],
        ),
        migrations.DeleteModel(
            name='HazardImages',
        ),
    ]
