# Generated by Django 6.0.7 on 2026-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0002_reportimages_delete_hazardimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardcategories',
            name='response_time',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
