# Generated by Django 6.0.7 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0003_hazardcategories_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreports',
            name='category',
        ),
        migrations.AddField(
            model_name='hazardreports',
            name='category',
            field=models.ManyToManyField(related_name='hazard_reports', to='apps_reports.hazardcategories'),
        ),
    ]
