# Generated by Django 6.0.7 on 2026-09-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0004_remove_hazardreports_category_hazardreports_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardreports',
            old_name='category',
            new_name='categories',
        ),
    ]
