# Generated by Django 6.0.7 on 2026-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0005_rename_category_hazardreports_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardcategories',
            old_name='response_time',
            new_name='response_time_days',
        ),
    ]
