# Generated by Django 6.0.7 on 2026-09-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0006_rename_response_time_hazardcategories_response_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimages',
            name='is_resolution',
            field=models.BooleanField(default=False),
        ),
    ]
