# Generated by Django 5.2.7 on 2026-09-15 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0007_reportimages_is_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreports',
            name='categories',
        ),
        migrations.AddField(
            model_name='hazardreports',
            name='categories',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='hazard_reports', to='apps_reports.hazardcategories'),
            preserve_default=False,
        ),
    ]
