# Generated by Django 5.2.7 on 2026-09-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0008_remove_hazardreports_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardreports',
            old_name='categories',
            new_name='category',
        ),
    ]
