# Generated by Django 5.2.7 on 2026-09-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0009_rename_categories_hazardreports_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreports',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
