# Generated by Django 5.2.7 on 2026-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0010_hazardreports_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreports',
            name='status',
            field=models.CharField(choices=[('NEW', 'Newly Submitted'), ('ASSIGNED', 'Assigned to Officer'), ('UNDER_REVIEW', 'Being worked on/Report Verification'), ('ON_HOLD', 'Out of Jurisdiction/Need External Department'), ('DISPATCHED', 'Dispatched Engineers'), ('RESOLVED', 'Issue is solved but needs user verification'), ('CLOSED', 'Automatically or manually closed')], db_index=True, default='NEW', max_length=20),
        ),
    ]
