# Generated by Django 6.0.7 on 2026-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_reports', '0011_alter_hazardreports_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreports',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('ON_HOLD', 'On-Hold'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20),
        ),
    ]
